; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lilygo-t-display-s3

[common]
build_flags = 
	-D VERSION=0.2
	-I"include/pid"
	-I"include/modbus"
	-I"include/devices"
	-I"include/www"
	-I"include/utils"
	-I"include/weather"
	-DUSE_ESP_IDF_LOG -DCORE_DEBUG_LEVEL=5
	-DLOGFILE_SYS='"/logSYS.txt"'
	-DLOGFILE_INVERTER='"/logInv.txt"'
	-DTAG='"EJunkies"'
	-DEJ=1
	-DWEB1=1
	-DCORS_DEBUG=1
	-DTEST_PID_WWWW=1
	-DMQTT='"10.0.0.4"'
	-DPID_LIB=1
	-DMODBUS_VERBOSE=1
	-DWEATHER_API=1
lib_deps_builtin = 
lib_deps_external = 
	emelianov/modbus-esp8266@^4.1.0
	bodmer/TFT_eSPI@^2.5.30
	ottowinter/ESPAsyncWebServer-esphome@^3.0.0
	esphome/AsyncTCP-esphome@^2.0.0
	bblanchon/ArduinoJson@^6.21.3
	fabianoriccardi/ESPLogger@^2.0.0
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
	br3ttb/PID@^1.2.1
	arduino-libraries/Arduino_JSON@^0.2.0
	knolleary/PubSubClient@^2.8

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
lib_deps = 
	${common.lib_deps_external}
board_build.f_cpu = 240000000L
upload_speed = 115200
upload_protocol = esptool
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_flags = 
	${common.build_flags}
	-DESP_LILY_GO

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
platform_packages = 
	framework-espidf @ https://github.com/espressif/esp-idf.git
framework = arduino
build_flags = 
	${common.build_flags}
	-DARDUINO_ESP32S3_DEV -DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DCORE_DEBUG_LEVEL=1 -DESP_S3
lib_deps = 
	${common.lib_deps_external}
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.memory_type = qio_opi
board_build.psram_type = opi
upload_speed = 115200
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = qio
debug_init_break = tbreak setup
