; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lilygo-t-display-s3



[common]
build_flags = 
	-g3  -Wall -Wextra  -Wstack-protector  -ftrapv
	-std=gnu++14
	-D VERSION=0.9
	-I"include/pid"
	-I"include/modbus"
	-I"include/devices"
	-I"include/www"
	-I"include/utils"
	-I"include/weather"
	-I"include/mainLoop" 
	-I "include/ai"
	-DUSE_ESP_IDF_LOG
	-DLOGFILE_SYS='"/logSYS.txt"'
	-DTAG='"EJunkies"'
	-DCORS_DEBUG=1
	-DTEST_PID_WWWW_=1
	-DMQTT1='"10.0.0.11"'
	-DMODBUS_VERBOSE1=1
	-DWEATHER_API='"https://api.open-meteo.com"'
	-DINFLUX1='"http://rantanplan-ethernet:8086"'
	-DFRONIUS_IV1=1
	-DCORE_DEBUG_LEVEL=4  ; 5 = Verbose, 4 = Debug
	-DHUAWEI_IV1=1
	-DAMIS_READER_DEV=1
	-DCARD_READER1=1
	-DLOG_DELTA_FORCE_WRITE=10000
	-DLOG_KEEP_ALIVE_TIME_IN_MS=60000
	-DLOG_DAY_TIME_IN_HOURS=6
	-DLOG_NIGHT_TIME_IN_HOURS=22
	-DSHELLY=1
	-DRUN_IT=1
	-DLOG_LEVEL_ESP=5
	-DLOG_LEVEL_ARD=4 
	-D configUSE_TRACE_FACILITY=1
    -D configUSE_STATS_FORMATTING_FUNCTIONS=1
    -DconfigMINIMAL_STACK_SIZE=2048
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
	-DCONFIG_FREERTOS_CHECK_STACKOVERFLOW=2
	-DIMMEDIATE_LOG_COUNT=3
	-DSMART_LOG_INTERVAL=5000
	-DTEMP_FILTER_SIZE=5
	-DTASK_TEMPERATURE_INTERVAL=20000
	-DTASK_WEBSOCKET_INTERVAL=10000
	-DTASK_MODBUS_AMISREADER_INTERVAL=40000
	-DTASK_NETWORK_MONITOR_INTERVAL=5000
	-DTASK_CLOCK_INTERVAL=10000
	-DTASK_PID_INTERVAL=2000
	-DTASK_MAINTANANCE_INTERVAL=60000
	-DHYSTERESIS_WATT=12
	-DLOW_BOUND_PWM=6
	-DBOILER=1
	-DPHASEN2_=1
	-DPHASEN2_WINDOW_SIZE=10000
	-DMIN_RELAY_SWITCH=500
lib_deps_builtin = 
lib_deps_external = 
	emelianov/modbus-esp8266@^4.1.0
	bodmer/TFT_eSPI@^2.5.30
	ottowinter/ESPAsyncWebServer-esphome@^3.0.0
	triggerncTCP-esphome@^2.0.0
	bblanchon/ArduinoJson@^7.0.0  
	fabianoriccardi/ESPLogger@^2.0.0
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
	arduino-libraries/Arduino_JSON@^0.2.0
	knolleary/PubSubClient@^2.8
	tobiasschuerg/ESP8266 Influxdb@^3.13.1

[env:lilygo-t-display-s3]
platform = espressif32
board_build.filesystem = littlefs
board = lilygo-t-display-s3
framework = arduino
lib_deps = ${common.lib_deps_external}
build_type = debug
monitor_filters = 
	esp32_exception_decoder
	time
	log2file
board_build.f_cpu = 240000000L
upload_speed = 115200
upload_protocol = esptool
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = dio
build_flags = 
	${common.build_flags}
	-DESP_LILY_GO

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
platform_packages = framework-espidf @ https://github.com/espressif/esp-idf.git
framework = arduino
board_build.filesystem = littlefs
build_type = debug
monitor_filters = 
	esp32_exception_decoder
	time
	log2file
build_flags = 
	${common.build_flags}
	-DARDUINO_ESP32S3_DEV -DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DCORE_DEBUG_LEVEL=1  -DESP_S3
lib_deps = ${common.lib_deps_external}
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.memory_type = qio_opi
board_build.psram_type = opi
upload_speed = 115200
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = dio
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0

[env:espwroom32]
platform = espressif32
framework = arduino
board = upesy_wroom
monitor_speed = 115200
build_type = debug
monitor_filters = 
	esp32_exception_decoder
	time
	log2file
build_flags = 
	${common.build_flags}
	-DESP_S3
lib_deps = ${common.lib_deps_external}
