#ifndef __MODBUS_REGISTER__H__
#define __MODBUS_REGISTER__H__

/*
https://github.com/lostcontrol/wattpilot

*/

#define INVERTER 1
#define MODBUS_BASE 40000 // 40001 -1

#define MODBUS_COMMMON MODBUS_BASE + 4
#define MODBUS_INVERTER_MANUFACTURER_LEN 16
#define MODBUS_INVERTER_DEVICE_LEN 16
#define MODBUS_INVERTER_OPTIONS 8
#define MODBUS_INVERTER_SW_VERS 8
#define MODBUS_INVERTER_SN 16
#define MODBUS_INVERTER_DEVICE_ADDDR 1

#define DC_POWER 40100
#define AC_POWER 40083 // PAC  AC POwer negativ if consuming
#define DC_CURRENT_COMMULATED 40072 = > IDC in solar web
#define DC_CURRENT_A 40073
#define DC_CURRENT_B
#define DC_CURRENT_C 40075
#define DC_SF 40076
#define DC_POWER  40101

#define MODBUS_COMMMON_LEN (MODBUS_INVERTER_MANUFACTURER_LEN + MODBUS_INVERTER_DEVICE_LEN + MODBUS_INVERTER_OPTIONS + MODBUS_INVERTER_SW_VERS + MODBUS_INVERTER_SN + MODBUS_INVERTER_DEVICE_ADDDR)

#endif